version: '3.3'
services:
    youtube-telegram-downloader:
        build: .
        env_file:
            - './bot.env'
        environment:
            - LOCAL_STORAGE_DIR=/home/bot/data
        volumes:
            - ./data:/home/bot/data
        restart: unless-stopped
